version: "3.7"

services:
    
    server:
        build: .
        volumes:
            - .:/code
        ports:
            - "0.0.0.0:${PORT}:${PORT}"
        depends_on:
            - redis
        env_file:
            - .env
    
    redis:
        image: redis:alpine
        command: redis-server --port 16379
        volumes:
            - ./redis-data:/data

    static_watch:
        build: .
        volumes:
            - .:/code
        command: 
            - yarn 
            - watch
