version: "3.7"

services:
    
    server:
        build: .
        volumes:
            - .:/code
        ports:
            - "0.0.0.0:5555:5555"
        depends_on:
            - redis
    
    redis:
        image: redis:alpine
        command: redis-server --port 16379
