version: "3.7"

services:

    server-test:
        build: .
        init: true
        command: uwsgi --http :${PORT} --gevent 1000 --http-websockets --master --wsgi-file server.py --callable app --socket versembrant_bruixit.sock
        ports:
            - "${PORT}:${PORT}"
        restart: always
        stop_signal: SIGINT
        user: 1000:1000
        depends_on:
            - redis
        volumes:
            - .:/code
        environment:
            - DEPLOY=1
            - FLASK_SECRET=hsau65aygasjhd5553ggjhff
        env_file:
            - .env
    
    redis-test:
        image: redis:alpine
        command: redis-server --port 16379
        volumes:
            - ./redis-data:/data
